# Generated by Django 2.0.6 on 2018-07-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, default='codigopadrao', max_length=15, null=True, unique=True),
        ),
    ]
